modifications to resolve syntax_type_naming issues
ashishawasthi/lapi pull request #1
Opened 2023-04-27 11:48 UTC by Tee-Hui

2023-04-27 11:49 UTC, Tee-Hui commented
1. requirement file renamed from "reqirement" to "requirement"
2. change list to List for pydantic model
3. changed json_string_from_file to text_from _file and changed .json to .txt in code. otherwise file not located error will show.
4. Optional syntax changed

2023-04-29 12:46 UTC, ashishawasthi commented on .DS_Store
please remove .DS_Store files

2023-04-29 12:46 UTC, ashishawasthi commented on assets/.DS_Store
please remove .DS_Store files

2023-04-29 12:46 UTC, ashishawasthi commented on assets/prompts/.DS_Store
please remove .DS_Store files

2023-04-29 12:48 UTC, ashishawasthi requested changes
I've added  .DS_Store to gitignore in your branch. if you cancel this PR and crate a new one, it should be good

2023-04-30 13:52 UTC, closed without merging